FROM ros:humble-perception

RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# Setting up working directory 
WORKDIR /ros2bag2video_workspace

# Add user
RUN adduser --quiet --disabled-password user
RUN chown -R user:user /ros2bag2video_workspace
USER user

ENTRYPOINT ["/ros_entrypoint.sh"]
